/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainticket.TicketBooking;

import DBM.FileManager;
import User.GUI_PassengerMainMenu;
import User.Passenger;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trainticket.GUI_buyTicket;
import trainticket.Train;

/**
 *
 * @author jingwen
 */
public class GUI_Booking extends javax.swing.JFrame {
    private JCheckBox [] seatCheckBoxes;
    private double totalFee = 0.0;
    private Passenger current_passenger;
    private Train buy_ticket;
    private ArrayList<String> selectedSeats = new ArrayList<>();
    private boolean seatsSelected = false;
    private Map<String, JCheckBox> seatCheckBoxMap = new HashMap<>();
    /**
     * Creates new form GUI_Booking
     */
    public GUI_Booking(Train buyTicket,Passenger currentPassenger) {
        initComponents();
        JCheckBox[] seatCheckBoxes = {
            A01, A02, A03, A04, A05, A06,
            B01, B02, B03, B04, B05, B06,
            C01, C02, C03, C04, C05, C06,
            D01, D02, D03, D04, D05, D06,
            E01, E02, E03, E04, E05, E06,
            F01, F02, F03, F04, F05, F06,
            G01, G02, G03, G04, G05, G06,
            H01, H02, H03, H04, H05, H06
        };
        for(int i = 0; i < seatCheckBoxes.length; i++){
            seatCheckBoxMap.put(seatCheckBoxes[i].getName(),seatCheckBoxes[i]);
        }
        this.current_passenger = currentPassenger;
        this.buy_ticket = buyTicket;
        String[] ScheduleData = new FileManager("src/Assets/trainschedules.txt").
                searchByPrimaryKey(buy_ticket.getTrainScheduleNumber());
        displayScheduleTable(ScheduleData);
        setCheckSeatDisable();
        
        for (JCheckBox checkBox : seatCheckBoxes) {
            checkBox.addActionListener(new ActionListener() {
            @Override
                public void actionPerformed(ActionEvent e) {
                calculateTotalFee(checkBox);
                updateTotalLabel();
                updateSelectedSeatsLabel(checkBox,selectedSeats);
                }
            });
        }
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        trainScheduleDetailsLabelHeading = new javax.swing.JLabel();
        TablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScheduleTable = new javax.swing.JTable();
        enterDetailsLabelHeading = new javax.swing.JLabel();
        businessClassPanel = new javax.swing.JPanel();
        businessClassLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        economyClassLabel = new javax.swing.JLabel();
        A03 = new javax.swing.JCheckBox();
        A02 = new javax.swing.JCheckBox();
        A01 = new javax.swing.JCheckBox();
        B03 = new javax.swing.JCheckBox();
        B02 = new javax.swing.JCheckBox();
        B01 = new javax.swing.JCheckBox();
        C01 = new javax.swing.JCheckBox();
        C02 = new javax.swing.JCheckBox();
        C03 = new javax.swing.JCheckBox();
        D03 = new javax.swing.JCheckBox();
        D01 = new javax.swing.JCheckBox();
        D02 = new javax.swing.JCheckBox();
        D06 = new javax.swing.JCheckBox();
        D05 = new javax.swing.JCheckBox();
        D04 = new javax.swing.JCheckBox();
        C04 = new javax.swing.JCheckBox();
        C05 = new javax.swing.JCheckBox();
        C06 = new javax.swing.JCheckBox();
        B06 = new javax.swing.JCheckBox();
        B05 = new javax.swing.JCheckBox();
        B04 = new javax.swing.JCheckBox();
        A04 = new javax.swing.JCheckBox();
        A05 = new javax.swing.JCheckBox();
        A06 = new javax.swing.JCheckBox();
        E04 = new javax.swing.JCheckBox();
        E05 = new javax.swing.JCheckBox();
        E06 = new javax.swing.JCheckBox();
        F06 = new javax.swing.JCheckBox();
        F05 = new javax.swing.JCheckBox();
        F04 = new javax.swing.JCheckBox();
        G04 = new javax.swing.JCheckBox();
        G05 = new javax.swing.JCheckBox();
        G06 = new javax.swing.JCheckBox();
        H06 = new javax.swing.JCheckBox();
        H05 = new javax.swing.JCheckBox();
        H04 = new javax.swing.JCheckBox();
        H01 = new javax.swing.JCheckBox();
        E03 = new javax.swing.JCheckBox();
        F03 = new javax.swing.JCheckBox();
        H02 = new javax.swing.JCheckBox();
        G03 = new javax.swing.JCheckBox();
        E01 = new javax.swing.JCheckBox();
        E02 = new javax.swing.JCheckBox();
        G02 = new javax.swing.JCheckBox();
        G01 = new javax.swing.JCheckBox();
        F02 = new javax.swing.JCheckBox();
        F01 = new javax.swing.JCheckBox();
        H03 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        jCheckBox49 = new javax.swing.JCheckBox();
        jLabel63 = new javax.swing.JLabel();
        jCheckBox50 = new javax.swing.JCheckBox();
        jLabel64 = new javax.swing.JLabel();
        seatsSelectedLabelScrollPane = new javax.swing.JScrollPane();
        seatsSelectedLabel = new javax.swing.JLabel();
        chooseSeatsLabelHeading = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        confirmAndPayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        trainScheduleDetailsLabelHeading.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        trainScheduleDetailsLabelHeading.setText("Train Schedule Details");
        trainScheduleDetailsLabelHeading.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ScheduleTable.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        ScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ScheduleID", "Train Number", "Departure Time", "Arrival Time", "Departure Location", "Arrival Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ScheduleTable);

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        enterDetailsLabelHeading.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        enterDetailsLabelHeading.setText("Enter Details:");
        enterDetailsLabelHeading.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        businessClassPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        businessClassLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        businessClassLabel.setText("Business Class");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setText("A01");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel6.setText("A02");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setText("A03");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel8.setText("A04");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel9.setText("A05");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel10.setText("A06");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel11.setText("B01");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel12.setText("B02");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel13.setText("B03");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel14.setText("B04");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel15.setText("B05");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel16.setText("B06");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel17.setText("C01");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel18.setText("C02");

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel19.setText("C03");

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel20.setText("D02");

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel21.setText("D03");

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel22.setText("D01");

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel23.setText("C04");

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel24.setText("C05");

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel25.setText("C06");

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel26.setText("D04");

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel27.setText("D05");

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel28.setText("D06");

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel29.setText("E01");

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel30.setText("E02");

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel31.setText("E03");

        jLabel32.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel32.setText("E04");

        jLabel33.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel33.setText("E05");

        jLabel34.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel34.setText("E06");

        jLabel35.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel35.setText("F01");

        jLabel36.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel36.setText("F02");

        jLabel37.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel37.setText("F03");

        jLabel38.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel38.setText("F04");

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel39.setText("F05");

        jLabel40.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel40.setText("F06");

        jLabel41.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel41.setText("G01");

        jLabel42.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel42.setText("G02");

        jLabel43.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel43.setText("G03");

        jLabel44.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel44.setText("G04");

        jLabel45.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel45.setText("G05");

        jLabel46.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel46.setText("G06");

        jLabel47.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel47.setText("H01");

        jLabel48.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel48.setText("H02");

        jLabel49.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel49.setText("H03");

        jLabel50.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel50.setText("H04");

        jLabel51.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel51.setText("H05");

        jLabel52.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel52.setText("H06");

        economyClassLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        economyClassLabel.setText("Economy Class");

        A03.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        A03.setName("A03"); // NOI18N
        A03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A03ActionPerformed(evt);
            }
        });

        A02.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        A02.setName("A02"); // NOI18N
        A02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A02ActionPerformed(evt);
            }
        });

        A01.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        A01.setName("A01"); // NOI18N
        A01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A01ActionPerformed(evt);
            }
        });

        B03.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        B03.setName("B03"); // NOI18N
        B03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B03ActionPerformed(evt);
            }
        });

        B02.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        B02.setName("B02"); // NOI18N
        B02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B02ActionPerformed(evt);
            }
        });

        B01.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        B01.setName("B01"); // NOI18N
        B01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B01ActionPerformed(evt);
            }
        });

        C01.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        C01.setName("C01"); // NOI18N

        C02.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        C02.setName("C02"); // NOI18N

        C03.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        C03.setName("C03"); // NOI18N

        D03.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        D03.setName("D03"); // NOI18N

        D01.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        D01.setName("D01"); // NOI18N

        D02.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        D02.setName("D02"); // NOI18N

        D06.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        D06.setName("D06"); // NOI18N

        D05.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        D05.setName("D05"); // NOI18N

        D04.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        D04.setName("D04"); // NOI18N

        C04.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        C04.setName("C04"); // NOI18N

        C05.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        C05.setName("C05"); // NOI18N

        C06.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        C06.setName("C06"); // NOI18N

        B06.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        B06.setName("B06"); // NOI18N
        B06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B06ActionPerformed(evt);
            }
        });

        B05.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        B05.setName("B05"); // NOI18N
        B05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B05ActionPerformed(evt);
            }
        });

        B04.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        B04.setName("B04"); // NOI18N
        B04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B04ActionPerformed(evt);
            }
        });

        A04.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        A04.setName("A04"); // NOI18N
        A04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A04ActionPerformed(evt);
            }
        });

        A05.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        A05.setName("A05"); // NOI18N
        A05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A05ActionPerformed(evt);
            }
        });

        A06.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        A06.setName("A06"); // NOI18N
        A06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A06ActionPerformed(evt);
            }
        });

        E04.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        E04.setName("E04"); // NOI18N

        E05.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        E05.setName("E05"); // NOI18N

        E06.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        E06.setName("E06"); // NOI18N

        F06.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        F06.setName("F06"); // NOI18N

        F05.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        F05.setName("F05"); // NOI18N

        F04.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        F04.setName("F04"); // NOI18N

        G04.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        G04.setName("G04"); // NOI18N

        G05.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        G05.setName("G05"); // NOI18N

        G06.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        G06.setName("G06"); // NOI18N

        H06.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        H06.setName("H06"); // NOI18N

        H05.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        H05.setName("H05"); // NOI18N

        H04.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        H04.setName("H04"); // NOI18N

        H01.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        H01.setName("H01"); // NOI18N

        E03.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        E03.setName("E03"); // NOI18N

        F03.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        F03.setName("F03"); // NOI18N

        H02.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        H02.setName("H02"); // NOI18N

        G03.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        G03.setName("G03"); // NOI18N

        E01.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        E01.setName("E01"); // NOI18N

        E02.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        E02.setName("E02"); // NOI18N

        G02.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        G02.setName("G02"); // NOI18N

        G01.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        G01.setName("G01"); // NOI18N

        F02.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        F02.setName("F02"); // NOI18N

        F01.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        F01.setName("F01"); // NOI18N

        H03.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        H03.setName("H03"); // NOI18N

        javax.swing.GroupLayout businessClassPanelLayout = new javax.swing.GroupLayout(businessClassPanel);
        businessClassPanel.setLayout(businessClassPanelLayout);
        businessClassPanelLayout.setHorizontalGroup(
            businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(businessClassPanelLayout.createSequentialGroup()
                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addComponent(A01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A03))
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addComponent(B01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B03))
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addComponent(C01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C03))
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addComponent(D01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D03))
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addComponent(E01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E03))
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addComponent(F01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F03))
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addComponent(G01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G03))
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addComponent(H01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H03)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel48)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel49))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel31))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel37))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel43)))
                                .addGap(75, 75, 75)
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel34))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel40))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel46))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel50)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel51)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel52)))
                                .addGap(18, 18, 18)
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(E04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E06))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(F04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(F05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(F06))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(G04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G06))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(H04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(H05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(H06)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21))
                                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7))
                                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13))
                                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19)))
                                        .addGap(75, 75, 75)
                                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16))
                                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10))
                                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel28))
                                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel25))))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(businessClassLabel)
                                        .addGap(74, 74, 74)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(A04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A06))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(B04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B06))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(C04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(C05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(C06))
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addComponent(D04)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(D05)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(D06))))))
                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(economyClassLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        businessClassPanelLayout.setVerticalGroup(
            businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(businessClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(businessClassLabel)
                .addGap(18, 18, 18)
                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(businessClassPanelLayout.createSequentialGroup()
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(businessClassPanelLayout.createSequentialGroup()
                                    .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(businessClassPanelLayout.createSequentialGroup()
                                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(A03, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(A02)
                                                .addComponent(A01)
                                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel13)))
                                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B03, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(B02)
                                            .addComponent(B01)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19)))
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C03, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(C02)
                                    .addComponent(C01)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D03, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(D02)
                                    .addComponent(D01))))
                        .addGroup(businessClassPanelLayout.createSequentialGroup()
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28))))
                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(A06, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(A05)
                                            .addComponent(A04))
                                        .addGap(32, 32, 32))
                                    .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(B06, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B05)
                                        .addComponent(B04)))
                                .addGap(32, 32, 32))
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(C06, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C05)
                                .addComponent(C04)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D06, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(D05)
                            .addComponent(D04))))
                .addGap(63, 63, 63)
                .addComponent(economyClassLabel)
                .addGap(18, 18, 18)
                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)))
                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(businessClassPanelLayout.createSequentialGroup()
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(businessClassPanelLayout.createSequentialGroup()
                                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(E06, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(E05)
                                            .addComponent(E04))
                                        .addGap(32, 32, 32))
                                    .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(F06, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(F05)
                                        .addComponent(F04)))
                                .addGap(32, 32, 32))
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(G06, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(G05)
                                .addComponent(G04)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H06, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(H05)
                            .addComponent(H04)))
                    .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(businessClassPanelLayout.createSequentialGroup()
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(businessClassPanelLayout.createSequentialGroup()
                                    .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(businessClassPanelLayout.createSequentialGroup()
                                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(E03, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(E02)
                                                .addComponent(E01))
                                            .addGap(32, 32, 32))
                                        .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(F03, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(F02)
                                            .addComponent(F01)))
                                    .addGap(32, 32, 32))
                                .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(G03, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(G02)
                                    .addComponent(G01)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(H03, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(H02)
                                .addComponent(H01)))
                        .addGroup(businessClassPanelLayout.createSequentialGroup()
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(jLabel30)
                                .addComponent(jLabel31))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(jLabel36)
                                .addComponent(jLabel37))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel41)
                                .addComponent(jLabel42)
                                .addComponent(jLabel43))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(businessClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel47)
                                .addComponent(jLabel48)
                                .addComponent(jLabel49)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel54.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel54.setText("Bank:");

        jLabel55.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel55.setText("Full Name:");

        jLabel57.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel57.setText("Card Number:");

        jLabel58.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel58.setText("Seats Selected:");

        jLabel59.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel59.setText("CVV Code:");

        jLabel60.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel60.setText("Total:");

        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        totalLabel.setText("-");
        totalLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBox49.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jLabel63.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel63.setText("I confirm that the information above are correct.");

        jCheckBox50.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jLabel64.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel64.setText("I have read and accepted the terms and conditions.");

        seatsSelectedLabelScrollPane.setBorder(null);
        seatsSelectedLabelScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        seatsSelectedLabelScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        seatsSelectedLabelScrollPane.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        seatsSelectedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        seatsSelectedLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        seatsSelectedLabelScrollPane.setViewportView(seatsSelectedLabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel59)
                                        .addComponent(jLabel57)
                                        .addComponent(jLabel55)
                                        .addComponent(jLabel54)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel58))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField1)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seatsSelectedLabelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel63))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel64)))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seatsSelectedLabelScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(totalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox50)
                    .addComponent(jLabel64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox49)
                    .addComponent(jLabel63))
                .addGap(21, 21, 21))
        );

        chooseSeatsLabelHeading.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        chooseSeatsLabelHeading.setText("Choose Seats");
        chooseSeatsLabelHeading.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cancelButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confirmAndPayButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        confirmAndPayButton.setText("Confirm & Pay");
        confirmAndPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAndPayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(chooseSeatsLabelHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enterDetailsLabelHeading)
                .addGap(176, 176, 176))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(trainScheduleDetailsLabelHeading)
                .addGap(345, 345, 345))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmAndPayButton))
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(businessClassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainScheduleDetailsLabelHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterDetailsLabelHeading)
                    .addComponent(chooseSeatsLabelHeading))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(businessClassPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmAndPayButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        GUI_buyTicket buyTicket = new GUI_buyTicket(current_passenger);
        buyTicket.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void A01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A01ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(A01);
    }//GEN-LAST:event_A01ActionPerformed

    private void A02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A02ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(A02);
    }//GEN-LAST:event_A02ActionPerformed

    private void A03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A03ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(A03);
    }//GEN-LAST:event_A03ActionPerformed

    private void A04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A04ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(A04);
    }//GEN-LAST:event_A04ActionPerformed

    private void A05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A05ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(A05);
    }//GEN-LAST:event_A05ActionPerformed

    private void A06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A06ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(A06);
    }//GEN-LAST:event_A06ActionPerformed

    private void B01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B01ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(B01);
    }//GEN-LAST:event_B01ActionPerformed

    private void B02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B02ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(B02);
    }//GEN-LAST:event_B02ActionPerformed

    private void B03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B03ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(B03);
    }//GEN-LAST:event_B03ActionPerformed

    private void B04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B04ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(B04);
    }//GEN-LAST:event_B04ActionPerformed

    private void B05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B05ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(B05);
    }//GEN-LAST:event_B05ActionPerformed

    private void B06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B06ActionPerformed
        // TODO add your handling code here:
//        calculateTotalFee(B06);
    }//GEN-LAST:event_B06ActionPerformed

    private void confirmAndPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAndPayButtonActionPerformed
        // TODO add your handling code here:
        if(!seatsSelected){
            JOptionPane.showMessageDialog(null,"Please select at least one seat.");
        }
        
        else if(jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty()
                || jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill in all your details.");
        }
        
        else if(!jCheckBox50.isSelected() || !jCheckBox49.isSelected()){
            JOptionPane.showMessageDialog(null,"Please ensure you have read the T&C's and check the Check Box.");
        }
        
        else{
            Booking new_booking = new Booking(buy_ticket, current_passenger, seatsSelectedLabel,
                    totalFee);
            JOptionPane.showMessageDialog(null,"You have successfully booked your tickets."
                    + " Please go to the 'Show My Bookings' to view your ticket");
            GUI_PassengerMainMenu passengerMainMenu = new GUI_PassengerMainMenu(current_passenger);
            passengerMainMenu.setVisible(true);
            dispose();
        }
        
        
    }//GEN-LAST:event_confirmAndPayButtonActionPerformed
    private void setCheckSeatDisable() {
        FileManager file = new FileManager("src/Assets/Bookings.txt");
        ArrayList<String[]> bookingData = file.saveTo2DArrayList();
        ArrayList<String[]> selectedTrainScheduleData = new ArrayList<>();
        // Get the Specific Train Schedule
        for (String[] data : bookingData) {
            if (data[2].equals(buy_ticket.getTrainScheduleNumber())) {
                selectedTrainScheduleData.add(data);
            }
        }

        // Disable checkboxes based on seat identifiers
        for (String[] trainScheduleArray : selectedTrainScheduleData) {
            String seatLine = trainScheduleArray[3];
            String[] seatArray = seatLine.split(":");
            for (String seat : seatArray) {
                JCheckBox checkBox = seatCheckBoxMap.get(seat);
                if (checkBox != null) {
                    checkBox.setEnabled(false);
                } else {
                    System.out.println("Invalid seat identifier: " + seat);
                }
            }
        }
    }
    
    
      
    public void displayScheduleTable(String[] scheduleData){
        //[{},{},{},....]
        //ArrayLIst with String Array
        DefaultTableModel model = (DefaultTableModel) ScheduleTable.getModel();
        model.addRow(scheduleData);
    }
    
//    private String[] getUnvailableSeats(){
//        String[] unavailableSeats;
//        
//        return null;
//    }
    
    public double calculateTotalFee(JCheckBox checkBox) {
        

        // Define seat fees based on checkbox name prefixes
        HashMap<String, Double> seatFees = new HashMap<>();
        seatFees.put("A", 50.0);
        seatFees.put("B", 50.0);
        seatFees.put("C", 50.0);
        seatFees.put("D", 50.0);
        seatFees.put("E", 20.0);
        seatFees.put("F", 20.0);
        seatFees.put("G", 20.0);
        seatFees.put("H", 20.0);
        
        String seatName = checkBox.getName();
        String prefix = seatName.substring(0, 1); 
        
        if (checkBox.isSelected()) {
            // Get the first character (prefix)
            if (seatFees.containsKey(prefix)) {
                totalFee += seatFees.get(prefix);
            }
        }else { // Checkbox is unchecked
            if (seatFees.containsKey(prefix)) {
                totalFee -= seatFees.get(prefix); // Subtract fee
            }
        }
        System.out.println(totalFee);
        return totalFee;
    }
    
    public void updateTotalLabel(){
        totalLabel.setText("RM" + String.valueOf(totalFee));
    }
    
    public void updateSelectedSeatsLabel(JCheckBox checkbox, ArrayList<String> selectedSeats) {
        // Assuming your label is named selectedSeatsLabel
        String labelText = seatsSelectedLabel.getText(); // Get the current text of the label
        String seatName = checkbox.getName(); // Get the text of the checkbox

        if (checkbox.isSelected()) {
            selectedSeats.add(seatName);
            
        } else {
            selectedSeats.remove(seatName); // Remove the seat information if the checkbox is deselected
        }
        String Text = String.join(":",selectedSeats);
        seatsSelectedLabel.setText(Text); // Set the updated text to the label
        seatsSelected = !seatsSelectedLabel.getText().isEmpty();
    }

    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI_Booking().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A01;
    private javax.swing.JCheckBox A02;
    private javax.swing.JCheckBox A03;
    private javax.swing.JCheckBox A04;
    private javax.swing.JCheckBox A05;
    private javax.swing.JCheckBox A06;
    private javax.swing.JCheckBox B01;
    private javax.swing.JCheckBox B02;
    private javax.swing.JCheckBox B03;
    private javax.swing.JCheckBox B04;
    private javax.swing.JCheckBox B05;
    private javax.swing.JCheckBox B06;
    private javax.swing.JCheckBox C01;
    private javax.swing.JCheckBox C02;
    private javax.swing.JCheckBox C03;
    private javax.swing.JCheckBox C04;
    private javax.swing.JCheckBox C05;
    private javax.swing.JCheckBox C06;
    private javax.swing.JCheckBox D01;
    private javax.swing.JCheckBox D02;
    private javax.swing.JCheckBox D03;
    private javax.swing.JCheckBox D04;
    private javax.swing.JCheckBox D05;
    private javax.swing.JCheckBox D06;
    private javax.swing.JCheckBox E01;
    private javax.swing.JCheckBox E02;
    private javax.swing.JCheckBox E03;
    private javax.swing.JCheckBox E04;
    private javax.swing.JCheckBox E05;
    private javax.swing.JCheckBox E06;
    private javax.swing.JCheckBox F01;
    private javax.swing.JCheckBox F02;
    private javax.swing.JCheckBox F03;
    private javax.swing.JCheckBox F04;
    private javax.swing.JCheckBox F05;
    private javax.swing.JCheckBox F06;
    private javax.swing.JCheckBox G01;
    private javax.swing.JCheckBox G02;
    private javax.swing.JCheckBox G03;
    private javax.swing.JCheckBox G04;
    private javax.swing.JCheckBox G05;
    private javax.swing.JCheckBox G06;
    private javax.swing.JCheckBox H01;
    private javax.swing.JCheckBox H02;
    private javax.swing.JCheckBox H03;
    private javax.swing.JCheckBox H04;
    private javax.swing.JCheckBox H05;
    private javax.swing.JCheckBox H06;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTable ScheduleTable;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JLabel businessClassLabel;
    private javax.swing.JPanel businessClassPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel chooseSeatsLabelHeading;
    private javax.swing.JButton confirmAndPayButton;
    private javax.swing.JLabel economyClassLabel;
    private javax.swing.JLabel enterDetailsLabelHeading;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel seatsSelectedLabel;
    private javax.swing.JScrollPane seatsSelectedLabelScrollPane;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel trainScheduleDetailsLabelHeading;
    // End of variables declaration//GEN-END:variables
}
