package User;


import javax.swing.JOptionPane;
import login.GUI_Login_Application;
import trainticket.GUI_searchTrainSchedule;
import trainticket.GUI_buyTicket;
import trainticket.GUI_ShowAllBookings;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jingwen
 */
public class GUI_PassengerMainMenu extends javax.swing.JFrame {
    private Passenger current_passenger;

    /**
     * Creates new form MainMenu
     */
    public GUI_PassengerMainMenu(Passenger currentPassenger) {
        this.current_passenger = currentPassenger;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        showTrainScheduleLabel = new javax.swing.JLabel();
        showAllBookingLabel = new javax.swing.JLabel();
        showPersonalInformationLabel = new javax.swing.JLabel();
        searchTrainScheduleLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(242, 189, 130));

        HeaderPanel.setBackground(new java.awt.Color(242, 219, 193));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("Welcome to ChooChoo Train Ticket Reservation System! ");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Below shows all actions that you can perform. Please choose one to continue.");

        logoutLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addContainerGap())
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(30, 30, 30))
        );

        InfoPanel.setBackground(new java.awt.Color(242, 219, 193));

        showTrainScheduleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        showTrainScheduleLabel.setText("1) Buy Ticket");
        showTrainScheduleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showTrainScheduleLabelMouseClicked(evt);
            }
        });

        showAllBookingLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        showAllBookingLabel.setText("3) Show All Bookings");
        showAllBookingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllBookingLabelMouseClicked(evt);
            }
        });

        showPersonalInformationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        showPersonalInformationLabel.setText("4) My Personal Information");
        showPersonalInformationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPersonalInformationLabelMouseClicked(evt);
            }
        });

        searchTrainScheduleLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        searchTrainScheduleLabel1.setText("2) Search Train Schedule with Source and Destination");
        searchTrainScheduleLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTrainScheduleLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showTrainScheduleLabel)
                    .addComponent(showAllBookingLabel)
                    .addComponent(showPersonalInformationLabel)
                    .addComponent(searchTrainScheduleLabel1))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(showTrainScheduleLabel)
                .addGap(18, 18, 18)
                .addComponent(searchTrainScheduleLabel1)
                .addGap(18, 18, 18)
                .addComponent(showAllBookingLabel)
                .addGap(18, 18, 18)
                .addComponent(showPersonalInformationLabel)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(HeaderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTrainScheduleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showTrainScheduleLabelMouseClicked
        // TODO add your handling code here:
        GUI_buyTicket gui_showTrainSchedule = new GUI_buyTicket(current_passenger);
        gui_showTrainSchedule.setVisible(true);
        dispose();
    }//GEN-LAST:event_showTrainScheduleLabelMouseClicked

    private void searchTrainScheduleLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTrainScheduleLabel1MouseClicked
        // TODO add your handling code here:
        GUI_searchTrainSchedule gui_searchTrainSchedule = new GUI_searchTrainSchedule(current_passenger);
        gui_searchTrainSchedule.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchTrainScheduleLabel1MouseClicked

    private void showAllBookingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllBookingLabelMouseClicked
        // TODO add your handling code here:
        GUI_ShowAllBookings showAllBookings = new GUI_ShowAllBookings(current_passenger);
        showAllBookings.setVisible(true);
        dispose();
    }//GEN-LAST:event_showAllBookingLabelMouseClicked

    private void showPersonalInformationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPersonalInformationLabelMouseClicked
        // TODO add your handling code here:
        GUI_PersonalInformation personalInfo = new GUI_PersonalInformation(current_passenger);
        personalInfo.setVisible(true);
        dispose();
    }//GEN-LAST:event_showPersonalInformationLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        GUI_Login_Application login = new GUI_Login_Application();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_PassengerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_PassengerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_PassengerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_PassengerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI_PassengerMainMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel searchTrainScheduleLabel1;
    private javax.swing.JLabel showAllBookingLabel;
    private javax.swing.JLabel showPersonalInformationLabel;
    private javax.swing.JLabel showTrainScheduleLabel;
    // End of variables declaration//GEN-END:variables
}
