/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User.admin;

import DBM.FileManager;
import DBM.InputValidation;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jingwen
 */
public class GUI_modifyTrainSchedule extends javax.swing.JFrame {
    private String trainScheduleID;
    private String originalTrainNumber;
    private String originalDepartureTime;
    private String originalArrivalTime;
    private String originalDepartureLocation;
    private String originalArrivalLocation;
    private String originalStatus;
    private boolean changesMade = false;
    

    /**
     * Creates new form GUI_modifyTrainSchedule
     */
    public GUI_modifyTrainSchedule() {
        initComponents();
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScheduleTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        trainScheduleIDLabel = new javax.swing.JLabel();
        departureTimeTextField = new javax.swing.JTextField();
        trainNumberTextField = new javax.swing.JTextField();
        arrivalTimeTextField = new javax.swing.JTextField();
        arrivalLocationTextField = new javax.swing.JTextField();
        departureLocationTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        makeChangesButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Modify Train Schedule");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        ScheduleTable.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        ScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ScheduleID", "Train Number", "Departure Location", "Arrival Location", "Departure Time", "Arrival Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScheduleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheduleTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ScheduleTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Please click on the schedule you want to modify above and fill in the details below.");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel3.setText("Departure Location:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel4.setText("Train Schedule ID: ");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setText("Train Number:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel6.setText("Departure Time:");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setText("Arrival Time:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel8.setText("Arrival Location:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel9.setText("Status:");

        trainScheduleIDLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        departureTimeTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        trainNumberTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        arrivalTimeTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        arrivalLocationTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        arrivalLocationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalLocationTextFieldActionPerformed(evt);
            }
        });

        departureLocationTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        departureLocationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureLocationTextFieldActionPerformed(evt);
            }
        });

        statusTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        statusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(trainNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(departureTimeTextField)
                            .addComponent(arrivalTimeTextField)
                            .addComponent(departureLocationTextField)
                            .addComponent(arrivalLocationTextField)
                            .addComponent(statusTextField)
                            .addComponent(trainScheduleIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(trainScheduleIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(trainNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(departureTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(arrivalTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departureLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(arrivalLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        makeChangesButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        makeChangesButton.setText("Make Changes");
        makeChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeChangesButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(makeChangesButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(makeChangesButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrivalLocationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalLocationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalLocationTextFieldActionPerformed

    private void departureLocationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureLocationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureLocationTextFieldActionPerformed

    private void statusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextFieldActionPerformed

    private void ScheduleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleTableMouseClicked
        // TODO add your handling code here:
        int row = ScheduleTable.rowAtPoint(evt.getPoint());

        if (row >= 0) {
            for (int column = 0; column < ScheduleTable.getColumnCount(); column++) {
                Object value = ScheduleTable.getValueAt(row, column);
                switch (column) {
                    case 0:
                        // Update trainScheduleIDLabel with the value of the first column
                        trainScheduleIDLabel.setText(value.toString());
                        trainScheduleID = value.toString();
                        break;
                    case 1:
                        // Update trainScheduleIDLabel with the value of the first column
                        trainNumberTextField.setText(value.toString());
                        originalTrainNumber = value.toString();
                        break;
                    case 2:
                        // Update departureTimeTextField with the value of the second column
                        departureTimeTextField.setText(value.toString());
                        originalDepartureTime = value.toString();
                        break;
                    case 3:
                        // Update arrivalTimeTextField with the value of the third column
                        arrivalTimeTextField.setText(value.toString());
                        originalArrivalTime = value.toString();
                        break;
                    case 4:
                        // Update departureLocationTextField with the value of the fourth column
                        departureLocationTextField.setText(value.toString());
                        originalDepartureLocation = value.toString();
                        break;
                    case 5:
                        // Update arrivalLocationTextField with the value of the fifth column
                        arrivalLocationTextField.setText(value.toString());
                        originalArrivalLocation = value.toString();
                        break;
                    case 6:
                        // Update statusTextField with the value of the sixth column
                        statusTextField.setText(value.toString());
                        originalStatus = value.toString();
                        break;
                    default:
                        // Handle additional columns if needed
                        break;
                }
            }
        }
    }//GEN-LAST:event_ScheduleTableMouseClicked

    private void makeChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeChangesButtonActionPerformed
        // TODO add your handling code here:
        boolean validTrainNo = false;
        boolean validTime = false;
        boolean validLocation = false;
        boolean validStatus = false;
        
        // Train Number
        if(InputValidation.isValidTrainNo(trainNumberTextField.getText())){
            validTrainNo = true;
        }
        else{
            JOptionPane.showMessageDialog(null, "Enter the correct TrainNo");
        }
        // Departure time and arrival time
        if(InputValidation.isValidTime(departureTimeTextField.getText()) && 
                InputValidation.isValidTime(arrivalTimeTextField.getText())){
            if(InputValidation.TimeCompare(departureTimeTextField.getText(), arrivalTimeTextField.getText())){
                validTime = true;
            }
            else{
                JOptionPane.showMessageDialog(null, "Arrival Time cannot be eariler than Departure Time.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid Time Format");
        }
        
        // Departure Location and Arrical Location
        if(!departureLocationTextField.getText().equals(arrivalLocationTextField.getText())){
            validLocation = true;
        }
        else{
            JOptionPane.showMessageDialog(null, "Departure Location cannot same to the Arrival Location");
        }
        
        // status
        if(statusTextField.getText().equals("Done") || statusTextField.getText().equals("Pending")){
            validStatus = true;
        }
        else{
            JOptionPane.showMessageDialog(null, "Status only 'Pending' or 'Done' ");
        }
        
        
        if(!trainNumberTextField.getText().equals(originalTrainNumber) || 
                !departureTimeTextField.getText().equals(originalDepartureTime) ||
                !arrivalTimeTextField.getText().equals(originalArrivalTime) || 
                !departureLocationTextField.getText().equals(originalDepartureLocation)||
                !arrivalLocationTextField.getText().equals(originalArrivalLocation) || 
                !statusTextField.getText().equals(originalStatus)){
            changesMade = true;
        }
        
        if(changesMade && validTrainNo && validTime && validLocation && validStatus){
            String[] newchanges= {
                trainScheduleID, trainNumberTextField.getText(), departureTimeTextField.getText(),
                arrivalTimeTextField.getText(), departureLocationTextField.getText(), arrivalLocationTextField.getText(),
                statusTextField.getText()
            };
            Admin newChanges = new Admin(newchanges);
            JOptionPane.showMessageDialog(null, "Train Schedule has been successfully changed.");
            GUI_AdminMainMenu GUI_adminMainMenu = new GUI_AdminMainMenu();
            GUI_adminMainMenu.setVisible(true);
            dispose();
        } else{
            JOptionPane.showMessageDialog(null, "No changes are made.");
        }   
        
        
    }//GEN-LAST:event_makeChangesButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GUI_AdminMainMenu adminMainMenu_gui = new GUI_AdminMainMenu();
        adminMainMenu_gui.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    
    public void displayTable(){
        // read dataline from file
        DefaultTableModel model = (DefaultTableModel) ScheduleTable.getModel();
        FileManager getrow = new FileManager("src/Assets/trainschedules.txt");
        ArrayList<String[]> rows =  getrow.saveTo2DArrayList();
        
        for(String[] row: rows){
            model.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI_modifyTrainSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI_modifyTrainSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI_modifyTrainSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI_modifyTrainSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI_modifyTrainSchedule().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ScheduleTable;
    private javax.swing.JTextField arrivalLocationTextField;
    private javax.swing.JTextField arrivalTimeTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField departureLocationTextField;
    private javax.swing.JTextField departureTimeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeChangesButton;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JTextField trainNumberTextField;
    private javax.swing.JLabel trainScheduleIDLabel;
    // End of variables declaration//GEN-END:variables
}
